language: r

r:
  - oldrel
  - release
  - devel
  
script:
  - R CMD build
  - R CMD check *tar.gz --as-cran

# for codecov
r_packages:
  - covr

# only report coverage after build is successful
after_success:
  - Rscript -e 'covr::codecov()'
